### ISSUE TITLE
it doesn't support the stream mode

### ISSUE THREAD

**Issue by fatwang2** [unclecode/groqcall#27]
hope you can support it, a little complex when coming to function calling with stream

**Comment by someshfengde** [comment]
@unclecode  can I try to fix up this issue? I'd like to contribute further onto this?

**Comment by someshfengde** [comment]
@fatwang2 The error is not from groqcall it's coming from phidata. 

After some research I've found that they are not allowing streaming responses for LLM calls.
The problem might be because they are casting `self.llm = cast(LLM, llm) ` over here https://github.com/phidatahq/phidata/blob/main/phi/task/llm/llm_task.py#L523
```
over above class the `invoke_stream` method is not implemented that might be cause of error and it's not passing the groq client instead it's using the pydantic basemodel. 
```


## Main error cause line 
https://github.com/phidatahq/phidata/blob/main/phi/task/llm/llm_task.py#L579

phidata is not supporting streaming for function calling.

**Comment by fatwang2** [comment]
I think you misunderstand my issue,you can post the API by yourself,with the stream=true

**Comment by fatwang2** [comment]
I think you don't need to solve this issue now, because groq is support function calling now

**Comment by someshfengde** [comment]
Thanks just saw their changelog it's awesome :)
